version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/.github/actions/tests/split_tests"
    schedule:
      interval: "daily"
    assignees:
      - "krzysztofczyz-da"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    # minor and patch version upgrades get pulled into a single PR
    # major versions create PRs one by one (for easier resolution)
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/" # For GitHub Actions '/' means .github/workflows/**/*.{yaml,yml}
    # Check for updates to GitHub Actions every week
    schedule:
      interval: "daily"
    assignees:
      - "krzysztofczyz-da"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/**/*.{yaml,yml}"
    # Check for updates to GitHub Actions every week
    schedule:
      interval: "daily"
    assignees:
      - "krzysztofczyz-da"
    groups:
      minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "krzysztofczyz-da"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    # minor and patch version upgrades get pulled into a single PR
    # major versions create PRs one by one (for easier resolution)
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
